-- Create product_images table
CREATE TABLE product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(255),
    alt_text VARCHAR(255),
    display_order INTEGER,
    image_url TEXT NOT NULL,
    is_thumbnail BOOLEAN,
    product_id BIGINT NOT NULL,
    variant_id BIGINT,
    FOREIGN KEY (product_id) REFERENCES products(id),
    FOREIGN KEY (variant_id) REFERENCES product_variants(id)
);
