-- Create orders table
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(255),
    canceled_reason TEXT,
    discount_amount NUMERIC(12,2),
    note TEXT,
    order_code VARCHAR(255) NOT NULL UNIQUE,
    shipping_fee NUMERIC(10,2),
    status VARCHAR(20) CHECK (status IN ('PENDING', 'PAID', 'SHIPPING', 'COMPLETED', 'CANCELED')),
    subtotal NUMERIC(12,2) NOT NULL,
    total_amount NUMERIC(12,2) NOT NULL,
    address_id BIGINT NOT NULL,
    shipping_method_id BIGINT,
    user_id BIGINT NOT NULL,
    voucher_id BIGINT,
    FOREIGN KEY (address_id) REFERENCES addresses(id),
    FOREIGN KEY (shipping_method_id) REFERENCES shipping_methods(id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (voucher_id) REFERENCES vouchers(id)
);

-- Create sequence for daily order numbering
-- This sequence resets daily and is used to generate sequential order codes
CREATE SEQUENCE order_daily_sequence
    START WITH 1
    INCREMENT BY 1
    NO MAXVALUE
    NO CYCLE;

-- Create order_items table
CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(255),
    price NUMERIC(10,2) NOT NULL,
    quantity INTEGER NOT NULL,
    total_price NUMERIC(12,2) NOT NULL,
    order_id BIGINT NOT NULL,
    variant_id BIGINT NOT NULL,
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (variant_id) REFERENCES product_variants(id)
);
