-- Create addresses table
CREATE TABLE addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(255),
    district VARCHAR(255) NOT NULL,
    is_default BOOLEAN,
    is_deleted BOOLEAN NOT NULL,
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    province VARCHAR(255) NOT NULL,
    receiver_name VARCHAR(255) NOT NULL,
    receiver_phone VARCHAR(15) NOT NULL,
    street_detail VARCHAR(255) NOT NULL,
    ward VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);
