-- Create product_variants table
CREATE TABLE product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(255),
    compare_at_price NUMERIC(10,2),
    is_deleted BOOLEAN NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    sku VARCHAR(100) NOT NULL UNIQUE,
    stock INTEGER NOT NULL,
    product_id BIGINT NOT NULL,
    FOREIGN KEY (product_id) REFERENCES products(id)
);
