-- Create vouchers table
CREATE TABLE vouchers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(255),
    code VARCHAR(50) NOT NULL UNIQUE,
    description TEXT,
    discount_type VARCHAR(20) NOT NULL CHECK (discount_type IN ('PERCENTAGE', 'FIXED_AMOUNT')),
    discount_value NUMERIC(10,2) NOT NULL,
    end_date TIMESTAMP(6) NOT NULL,
    is_active BOOLEAN,
    is_deleted BOOLEAN NOT NULL,
    max_discount_amount NUMERIC(10,2),
    min_order_value NUMERIC(10,2),
    name VARCHAR(255) NOT NULL,
    start_date TIMESTAMP(6) NOT NULL,
    usage_limit INTEGER,
    usage_per_user INTEGER,
    used_count INTEGER
);

-- Create user_vouchers junction table
CREATE TABLE user_vouchers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(255),
    is_deleted BOOLEAN NOT NULL,
    user_id BIGINT NOT NULL,
    voucher_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (voucher_id) REFERENCES vouchers(id)
);

