-- Create shipping_methods table
CREATE TABLE shipping_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(255),
    base_fee NUMERIC(10,2) NOT NULL,
    code VARCHAR(50) NOT NULL,
    description TEXT,
    estimated_days INTEGER,
    fee_per_km NUMERIC(10,2),
    is_active BOOLEAN,
    logo_url TEXT,
    name VARCHAR(100) NOT NULL UNIQUE
);
