-- Create payment_methods table
CREATE TABLE payment_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(255),
    description TEXT,
    is_active BOOLEAN,
    logo_url VARCHAR(255),
    name VARCHAR(100) NOT NULL UNIQUE
);
