-- Create payments table
CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(255),
    amount NUMERIC(12,2) NOT NULL,
    failed_reason TEXT,
    payment_date TIMESTAMP(6),
    status VARCHAR(30) NOT NULL CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED', 'EXPIRED')),
    transaction_id VARCHAR(255) UNIQUE,
    pay_url TEXT,
    order_id BIGINT NOT NULL UNIQUE,
    payment_method_id BIGINT NOT NULL,
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (payment_method_id) REFERENCES payment_methods(id)
);
