-- Create product_reviews table
CREATE TABLE product_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(255),
    comment TEXT,
    is_deleted BOOLEAN NOT NULL,
    is_verified_purchase BOOLEAN,
    rating INTEGER NOT NULL,
    review_date TIMESTAMP(6),
    order_id BIGINT,
    product_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    variant_id BIGINT,
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (product_id) REFERENCES products(id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (variant_id) REFERENCES product_variants(id)
);
