CREATE TABLE otp
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email       VARCHAR(255),
    otp         VARCHAR(255),
    purpose     VARCHAR(255),
    expiry_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_otp PRIMARY KEY (id)
);