-- Create product_variants table
CREATE TABLE product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(255),
    compare_at_price NUMERIC(10,2),
    is_deleted BOOLEAN NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    sku VARCHAR(100) NOT NULL UNIQUE,
    stock INTEGER NOT NULL,
    product_id BIGINT NOT NULL,
    FOREIGN KEY (product_id) REFERENCES products(id)
);

-- Create sequence for SKU auto-generation
-- Format: GLM-{5-digit} (e.g., GLM-00001, GLM-00002, GLM-99999, GLM-100000)
-- GLM = GLaMora brand identifier
CREATE SEQUENCE sku_sequence
    START WITH 1
    INCREMENT BY 1
    NO MAXVALUE
    NO CYCLE;
