-- Create attributes table
CREATE TABLE attributes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(255),
    name VARCHAR(100) NOT NULL UNIQUE
);

-- Create attribute_values table
CREATE TABLE attribute_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(255),
    value VARCHAR(100) NOT NULL,
    attribute_id BIGINT,
    FOREIGN KEY (attribute_id) REFERENCES attributes(id)
);

-- Create product_variant_values junction table
CREATE TABLE product_variant_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(255),
    attribute_value_id BIGINT NOT NULL,
    variant_id BIGINT NOT NULL,
    FOREIGN KEY (attribute_value_id) REFERENCES attribute_values(id),
    FOREIGN KEY (variant_id) REFERENCES product_variants(id),
    UNIQUE (variant_id, attribute_value_id)
);
